### ISSUE TITLE
Submod

### ISSUE THREAD

**Issue by ghost** [CaptainHorse/MAS-Additions#8]
Hello i want to download the face recognition submod but how

I use linux

**Comment by DatCaptainHorse** [comment]
Didn't notice this issue was left without answer until now, sorry.

The submod is currently not updated and worked on, I did try to make it work on Linux side but things are not working well on that side, until CPython (and Python) stops being the antiquated thing it is, I won't be able to make the submod work on Linux side.

Refer to the issue https://github.com/CaptainHorse/MAS-Additions/issues/1

As for downloading, Releases tab is the one you want to look for, on new Github site it's to the right on main page.
